# command to run: docker-compose up -d
services:
  mongodb:
    image: mongo:latest
    container_name: pydocflow-mongodb
    ports:
      - "27017:27017"  # Map host port 27017 to container port 27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - documents_data:/data/db  # Persist data in a named volume
volumes:
  documents_data:  # Declare the volume
